2025-06-03 02:26:15,746 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:26:25,960 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:26:36,124 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:26:46,331 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:26:56,665 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:27:06,828 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:27:17,113 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:28:44,791 - __main__ - INFO - Starting Deriv Smart Signal Bot in TEST MODE...
2025-06-03 02:28:51,297 - __main__ - INFO - Waiting 8.7 seconds until reminder
2025-06-03 02:28:52,009 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getMe "HTTP/1.1 200 OK"
2025-06-03 02:28:52,176 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/deleteWebhook "HTTP/1.1 200 OK"
2025-06-03 02:28:52,179 - telegram.ext.Application - INFO - Application started
2025-06-03 02:29:02,673 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:29:12,842 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:29:23,018 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:29:33,194 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:29:43,413 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:29:55,001 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:38:14,689 - __main__ - INFO - Starting Deriv Signal Bot
2025-06-03 02:38:20,221 - __main__ - INFO - Waiting 26379.8s until reminder
2025-06-03 02:38:20,898 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getMe "HTTP/1.1 200 OK"
2025-06-03 02:38:21,066 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/deleteWebhook "HTTP/1.1 200 OK"
2025-06-03 02:38:21,069 - telegram.ext.Application - INFO - Application started
2025-06-03 02:38:31,570 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:38:41,981 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:38:52,145 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:39:02,309 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:39:12,479 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:39:22,662 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:39:32,847 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:39:43,177 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:39:53,368 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:40:03,916 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:40:16,415 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:40:27,260 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:40:40,578 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:40:50,776 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:41:00,942 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:41:11,117 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:41:21,426 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:41:31,596 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:41:41,756 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:41:51,919 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:42:02,079 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:42:12,270 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:42:22,492 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:42:32,652 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:42:42,813 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:42:52,976 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:43:03,137 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:43:13,577 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:43:24,371 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:43:34,552 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:43:44,867 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:43:55,040 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:44:05,375 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:44:16,353 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:44:28,227 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:44:38,420 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:44:48,599 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:44:58,768 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:45:21,018 - __main__ - INFO - Starting TEST MODE in EAT Time
2025-06-03 02:45:28,884 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getMe "HTTP/1.1 200 OK"
2025-06-03 02:45:29,571 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/deleteWebhook "HTTP/1.1 200 OK"
2025-06-03 02:45:29,575 - telegram.ext.Application - INFO - Application started
2025-06-03 02:45:41,870 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:45:52,500 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:46:03,153 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:46:13,323 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:46:23,496 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:46:33,708 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:46:44,301 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:46:59,139 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:47:09,315 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:47:19,788 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:47:30,139 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:47:40,440 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:47:50,611 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:48:00,809 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:48:10,979 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:48:21,146 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:48:31,344 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:48:41,518 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:48:51,685 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:49:01,992 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:51:27,075 - __main__ - INFO - Starting Deriv Signal Bot in TEST MODE
2025-06-03 02:51:34,707 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getMe "HTTP/1.1 200 OK"
2025-06-03 02:51:35,325 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/deleteWebhook "HTTP/1.1 200 OK"
2025-06-03 02:51:35,329 - telegram.ext.Application - INFO - Application started
2025-06-03 02:51:47,270 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:51:59,006 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:52:09,456 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:52:21,429 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:52:31,600 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:52:41,900 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:52:52,080 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:53:02,259 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:53:12,457 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:53:23,681 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:53:33,922 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:53:44,171 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:53:54,351 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:54:04,531 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:54:14,701 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:54:24,875 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:54:35,053 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:54:45,237 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:54:56,695 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:55:06,871 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:55:19,469 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:55:29,640 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:55:40,649 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:55:50,833 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:56:02,007 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:56:12,190 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:56:22,368 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:56:32,541 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:56:42,710 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:56:52,887 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:57:03,066 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:57:13,561 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:57:23,789 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:57:33,964 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:57:44,172 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:57:54,346 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:58:04,540 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:58:14,740 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:58:25,359 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:58:35,675 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:58:49,082 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:58:59,276 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:59:10,151 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 02:59:21,072 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:01:17,075 - __main__ - WARNING - Error processing message: 
2025-06-03 03:01:17,141 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 273, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_updater.py", line 335, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 669, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 4601, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 697, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 369, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 726, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 197, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 304, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 297, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-06-03 03:01:18,385 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 273, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_updater.py", line 335, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 669, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 4601, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 697, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 369, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 726, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 197, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 304, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 297, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-06-03 03:01:19,924 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 273, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_updater.py", line 335, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 669, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 4601, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 697, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 369, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 726, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 197, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 304, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 297, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-06-03 03:01:22,220 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 273, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_updater.py", line 335, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 669, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 4601, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 697, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 369, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 726, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 197, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 304, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 297, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-06-03 03:01:25,610 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 273, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 115, in network_retry_loop
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_utils\networkloop.py", line 108, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_updater.py", line 335, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 669, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 4601, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 697, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\ext\_extbot.py", line 369, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\_bot.py", line 726, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 197, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_baserequest.py", line 304, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Lenovo\bot_master\venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 297, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-06-03 03:01:27,097 - __main__ - WARNING - Error processing message: 
2025-06-03 03:01:36,334 - __main__ - ERROR - WebSocket connection failed (attempt 1/3): no close frame received or sent
2025-06-03 03:01:54,490 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:02:04,663 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:02:14,836 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:02:25,061 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:02:35,335 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:02:45,504 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:02:55,678 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:03:05,841 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:03:16,017 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:03:26,192 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:03:36,374 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:03:46,610 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:03:56,807 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:04:08,014 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:04:18,392 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:04:29,145 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:04:39,365 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:04:49,534 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
2025-06-03 03:04:59,716 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7227653802:AAGwjUiWjVT4N6mabmxLZ62jbPzsklcEHZM/getUpdates "HTTP/1.1 200 OK"
